### ISSUE TITLE
Do you have a ROS1 version

### ISSUE THREAD

**Issue by Summit-SLAM** [paagutie/dvl-a50#1]
Hi 
My system is ROS melodic, do you have package suit for ROS1 version ?

I want know how to get the IMU output ?

**Comment by paagutie** [comment]
Hi, 
Unfortunately the project was intended for environments under ROS 2, but it is not difficult to export it to ROS1. In fact the core is in a TCP client and json for handling the information received through the socket. That said, the classes are independent of the ROS version and can be integrated in any of its versions.

Apparently with the current sensor firmware it's not possible to get IMU data directly, but only dead reckoning. In my case I have been working with an external IMU sensor to perform my own sensor fusion using the speed data from the DVL sensor.

**Comment by Summit-SLAM** [comment]
> Hi, Unfortunately the project was intended for environments under ROS 2, but it is not difficult to export it to ROS1. In fact the core is in a TCP client and json for handling the information received through the socket. That said, the classes are independent of the ROS version and can be integrated in any of its versions.
> 
> Apparently with the current sensor firmware it's not possible to get IMU data directly, but only dead reckoning. In my case I have been working with an external IMU sensor to perform my own sensor fusion using the speed data from the DVL sensor.
